#!/bin/zsh
#
# Basic wrapper for wal/pywal to set the wallpaper and choose a backend
# Usage: wp FILENAME BACKEND SATURATION
# Available backends:
#   colorz
#   colorthief
#   schemer2
#   wal
#   haishoku
#
# TODO: Error handling

function backend() {
    echo ${wal --backend}
}


function set_wallpaper() {
    clear
    local file="${1?}"
    local backend="${2:-wal}"
    local saturation="${3:-1.0}"
    echo "Exec: wal -i /usr/share/backgrounds/$file.jpg --backend $backend --saturate $saturate -p $file"
    wal -i /usr/share/backgrounds/$file.jpg --backend $backend --saturate $saturation -p $file
}

if [ ${1?} = "be" ]
then
    backend
else
    set_wallpaper $1 $2 $3
fi

